version: '2'
services:
  angular_moviemasher:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ~/angular-moviemasher/angular-moviemasher:/var/www/html

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  api:
    build: api/.
    ports: 
      - "8081:80"
    volumes:
      - ~/angular-moviemasher/api/CharlieChaplin:/var/www/html

  moviemasher_rb:
    image: moviemasher/moviemasher.rb:latest
    volumes_from:
      - angular_moviemasher
    command: process_loop
    tty: true

  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    links:
      -  angular_moviemasher
